### ISSUE TITLE
Unexpected transitive dependency in a graph when using `belongsTo` alignment

### ISSUE THREAD

**Issue by chali** [nebula-plugins/gradle-nebula-integration#26]
I have this project https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/unexpected-module-with-alignment where I'm getting one more dependency in my graph when I start using alignment implemented through `belongsTo`

`./gradlew -Dnebula.features.coreAlignmentSupport=true dI --dependency com.google.protobuf:protobuf-lite --configuration compile`

Returns

```
> Task :dependencyInsight
com.google.protobuf:protobuf-lite:3.0.1
   variant "runtime" [
      org.gradle.status = release (not requested)
      org.gradle.usage  = java-runtime (not requested)
   ]

com.google.protobuf:protobuf-lite:3.0.1
\--- io.grpc:grpc-protobuf-lite:1.10.0
     +--- compile
     \--- io.grpc:grpc-protobuf:1.10.0
          +--- compile
          \--- compile
```

`./gradlew -Dnebula.features.coreAlignmentSupport=false dI --dependency com.google.protobuf:protobuf-lite --configuration compile`

```
Task :dependencyInsight
No dependencies matching given input were found in configuration ':compile'
```

**Comment by bigdaz** [comment]
In your report above, you've got `-Dnebula.features.coreAlignmentSupport=false` in both cases. I can reproduce the behaviour you're describing by switching between `true` and `false` for this property. Am I correct in assuming that this switches between using the original Nebula `align` rules, and using the new `belongsTo` API?

Looking at the [POM file for `io.grpc:grpc-protobuf-lite:1.10.0`](http://central.maven.org/maven2/io/grpc/grpc-protobuf-lite/1.10.0/grpc-protobuf-lite-1.10.0.pom) it looks  `com.google.protobuf:protobuf-lite:3.0.1` _should_ be brought in as a transitive dependency.

Here's the portion of `dependencies` report with `-Dnebula.features.coreAlignmentSupport=false`:
```
compile - Dependencies for source set 'main' (deprecated, use 'implementation' instead).
\--- io.grpc:grpc-protobuf:1.10.0
     \--- io.grpc:grpc-protobuf-lite:1.10.0
          +--- io.grpc:grpc-core:1.10.0 (*)
          \--- com.google.guava:guava:19.0 (*)
```

And here it is with `-Dnebula.features.coreAlignmentSupport=true`:
```
compile - Dependencies for source set 'main' (deprecated, use 'implementation' instead).
\--- io.grpc:grpc-protobuf:1.10.0
     \--- io.grpc:grpc-protobuf-lite:1.10.0
          +--- io.grpc:grpc-core:1.10.0 (*)
          +--- com.google.protobuf:protobuf-lite:3.0.1
          \--- com.google.guava:guava:19.0 (*)
```

My hunch is that this is actually an issue with the 'non-core' alignment support omitting a dependency that should be included. This could be due to multiple modules having the same name: `protobuf-lite`.

**Comment by bigdaz** [comment]
Ah, it's an exclusion that I guess is being ignored somehow when `belongsTo` gets involved. I'll see if @melix can investigate.

The [POM for `io.grpc:grpc-protobuf:1.10.0`](http://central.maven.org/maven2/io/grpc/grpc-protobuf/1.10.0/grpc-protobuf-1.10.0.pom) brings in `io.grpc:grpc-protobuf-lite:1.10.0` but excludes `com.google.protobuf:protobuf-lite` from the path:

```
<dependency>
  <groupId>io.grpc</groupId>
  <artifactId>grpc-protobuf-lite</artifactId> 
  <version>1.10.0</version>
  <scope>compile</scope>
  <exclusions>
    <exclusion>
      <artifactId>protobuf-lite</artifactId>
      <groupId>com.google.protobuf</groupId>
    </exclusion>
  </exclusions>
</dependency>
```
