### ISSUE TITLE
Dependency insight: Rejections do not show up as a contributor when user has not selected a dynamic version

### ISSUE THREAD

**Issue by OdysseusLives** [nebula-plugins/gradle-nebula-integration#5]
## Scenario
Given a build file containing a dependency with a rejection and non-dynamic version selection: 
```
dependencies {
    compile 'com.google.guava:guava:18.0'
}

import org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionSelectorScheme
import org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionComparator
configurations.all {
    resolutionStrategy.componentSelection.all({ selection ->
        def candidate = selection.candidate
        def rejectionMessage = '✭ rejection of com.google.guava:guava:16.0.1'
        if (candidate.group == 'com.google.guava' && candidate.module == 'guava') {
            def comparator = new DefaultVersionComparator()
            def scheme = new DefaultVersionSelectorScheme(comparator)

            def versionSelector = scheme.parseSelector('16.0.1')
            if (candidate.version == null || candidate.version == '' || versionSelector.accept(candidate.version)) {
                selection.reject(rejectionMessage)
            }
        }
    })
}
```

when I run `./gradlew dependencyInsight --dependency guava` 
with Gradle 4.10-20180801000007+0000

then I should see the final version as `18.0` (which I do)
and I should see a selection reason as `Rejection : 16.0.1 by rule because...` (which I do *not*)
**Note**: See full output below

## Example Project
Please see the whole example project at [dependency-insight/docs/reject/reject-static/input](https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/dependency-insight/docs/reject/reject-static/input)

----------

## Current output for reference
```
> Task :dependencyInsight
com.google.guava:guava:18.0
   variant "compile" [
      org.gradle.status = release (not requested)
      org.gradle.usage  = java-api
   ]

com.google.guava:guava:18.0
\--- compileClasspath
```

**Comment by melix** [comment]
So in the linked example, the only requested version is `18`, so the rejection is never applied: this line returns `false`:

`if (candidate.version == null || candidate.version == '' || versionSelector.accept(candidate.version))`

(because the only version it sees is 18). So there's no rejection. If I change the script to:

```
dependencies {
    compile 'com.google.guava:guava:16.0.1'
    compile 'com.google.guava:guava:18.0'
}
```

(intentionally adding the same dependency twice), then the rule is _not called either_ because conflict resolution kicks in first. So the version is never rejected.

What Gradle will show is when a rejection is effectively _called_, so something like this would:

```
dependencies {
    compile('com.google.guava:guava:[16.0,16.0.1]')
    compile 'com.google.guava:guava:18.0'
}
```
