### ISSUE TITLE
Submodule jar is not built as part of submodule dependency.

### ISSUE THREAD

**Issue by chali** [nebula-plugins/gradle-nebula-integration#59]
My expectation is when you have a submodule dependency:
```
//project :impl

dependencies {
    api project(':api')
}
```

When I build `./gradlew :impl` I will see as part of the output:
```
> Task :api:jar
```
However, that is not the case in this project. https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/jar-not-build

You can run `./gradlew :impl:classes`

To get:
```
> Task :lib:compileJava
> Task :lib:processResources NO-SOURCE
> Task :lib:classes
> Task :lib:jar
> Task :api:compileJava
> Task :impl:compileJava
> Task :impl:processResources NO-SOURCE
> Task :impl:classes

BUILD SUCCESSFUL in 0s
4 actionable tasks: 4 executed
```

**Comment by ljacomet** [comment]
What you see is the illustration of a key difference between the `java` and `java-library` plugin.

With the `java` plugin, the `runtimeElements` and `apiElements` outgoing configurations both only have the variant with the `jar` artifact. That means that either for compiling or running, anything that requests `java-api` or `java-runtime` can only consume the `jar` produced by the project.

However with the `java-library` plugin, there is another variant registered with `apiElements`, the `classes` one. That variant produces a `org.gradle.usage=java-api-classes` which is sourced from the main source set `compileJava` task _and_ is compatible with the `java-api` usage request.
It effectively states that for compilation, we can use directly the produced class file without the need for a `jar` to be built.

That's why only `api:compileJava` is executed.

Is the question just informative or is that causing unexpected missing jar files in a project?

**Comment by chali** [comment]
The situation is the proper behavior of `java-library` plugin.
