### ISSUE TITLE
Reading transitive dependencies from GMM file produces unexpected results

### ISSUE THREAD

**Issue by rpalcolea** [nebula-plugins/gradle-nebula-integration#65]
Given this build file: https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/read-transitive-dependencies-module-issue/build.gradle, when running `printTransitiveDependencies` task, I'd expect the following output:

```
> Task :printTransitiveDependencies
[gid:baf:3.0-rc.1]
```

However, this is not the case when `gradle metadata` is enabled. Adding the `ignoreGradleMetadataRedirection` flag produces expected results

This is the POM https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/read-transitive-dependencies-module-issue/testrepogen/mavenrepo/netflix/nebula-release-playground-common/0.1.0-rc.1/nebula-release-playground-common-0.1.0-rc.1.pom
and the gradle metadata file https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/read-transitive-dependencies-module-issue/testrepogen/mavenrepo/netflix/nebula-release-playground-common/0.1.0-rc.1/nebula-release-playground-common-0.1.0-rc.1.module and a test repo inside this project: https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/read-transitive-dependencies-module-issue/testrepogen/mavenrepo

What we do is create a new dependency in `runtime` configuration. Note that this doesn't appear to work with `runtimeOnly`  when doing `project.dependencies.create`.

Once we created this dependnecy, we create a detached configuration with the dependency and resolve it. Then we read the transitives to do some validations.

When the GMM file is loaded via the redirection header, the transitives are not part of `dep.selected.getDependencies()`.

We noticed this in some tests when upgrading to 6.x but the behavior is present in current stable release

**Comment by ljacomet** [comment]
So this is interesting.

The issue comes from the mix up of legacy `configuration` based selection and the usage of Gradle Module Metadata.
Without GMM, you effectively select the Maven `runtime` configuration, all is good, you get your dependencies.

With GMM, we allow you to select the `runtime` configuration, because we consider it always exists. However that's wrong when the metadata source is GMM. And thus you end up with a configuration that has no dependencies.

I am looking at making this an error in Gradle 6.0, since we cannot change the behavior in Gradle 5.x.

Because then it would be much clearer that you are attempting to select something that does not exist.

The fix, valid for both 5.x and 6.x, is to move to attributes based selection instead of using a `configuration`.

**Comment by ljacomet** [comment]
FYI gradle/gradle#10976

**Comment by rpalcolea** [comment]
Thanks for looking into it @ljacomet.

Made changes in https://github.com/nebula-plugins/gradle-nebula-integration/commit/d8a62cfa6951981913318f3839a65160d06a92f8#diff-6f15e94f7af2fe14dbb1ab28c39b1e02 and it works. Will translate this to our internal tooling.

Closing this now!
